### ISSUE TITLE
error in training srgan

### ISSUE THREAD

**Issue by sronast** [krasserm/super-resolution#37]
While running this function in file -------'example-srgan.ipynb'----- 
gan_trainer.train(train_ds, steps=200000)

AttributeError: 'Operation' object has no attribute '_graph'

**Comment by krasserm** [comment]
Which Tensorflow version are you using?

**Comment by sronast** [comment]
2.1

**Comment by krasserm** [comment]
Ok thanks, will look into it later this week ...

**Comment by krasserm** [comment]
I just upgraded to TF 2.1 using the following conda environment

```yml
name: sisr
dependencies:
- python=3.6
- pip
- tqdm=4.32.1
- Pillow=6.0.0
- matplotlib=3.1.1
- pip:
  - tensorflow==2.1.0
  - tensorflow-addons==0.7.0
```

and I can run training in `example-srgan.ipynb` without any errors. Please create a new environment using the above specification and try running the notebook again.

If the error persists, please re-open this ticket incl. a `conda list` output and a description of changes you've made to the notebook (if any).

Will push the TF 2.1 upgrade to master soon.
